#!/usr/bin/env ruby -w

require 'blue_conductor'

if ARGV.count == 0
  puts "You must provide a band and song name"
  exit
end

band = ARGV.first
song = ARGV.last

track = BlueConductor.song_for(band, song)

puts '*'*100
puts "Band: #{track.band}"
puts "Title: #{track.title}"
puts "Album: #{track.album}"
puts "Lyrics:"
puts '-'*100
puts track.lyrics
puts '*'*100

